import type { Metadata } from 'next';
import { Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { Suspense } from 'react';
import Loading from '@/components/Loading';
import Copyright from '@/components/Copyright';

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Smart Search Reader',
    description: 'Generated by Sepehr Doraghi',
    icons: {
        icon: '/icons/pwa/icon-192x192.png',
        shortcut: '/icons/pwa/icon-192x192.png',
        apple: '/icons/pwa/icon-192x192.png',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <head>
                <meta name='application-name' content='PWA App' />
                <meta name='apple-mobile-web-app-capable' content='yes' />
                <meta
                    name='apple-mobile-web-app-status-bar-style'
                    content='default'
                />
                <meta name='apple-mobile-web-app-title' content='PWA App' />
                <meta name='description' content='Best PWA App in the world' />
                <meta name='format-detection' content='telephone=no' />
                <meta name='mobile-web-app-capable' content='yes' />
                <meta
                    name='msapplication-config'
                    content='/icons/browserconfig.xml'
                />
                <meta name='msapplication-TileColor' content='#2B5797' />
                <meta name='msapplication-tap-highlight' content='no' />
                <meta name='theme-color' content='#000000' />

                <link
                    rel='icon'
                    type='image/png'
                    sizes='48x48'
                    href='/icons/icon-48x48.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='72x72'
                    href='/icons/icon-72x72.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='96x96'
                    href='/icons/icon-96x96.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='128x128'
                    href='/icons/icon-128x128.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='144x144'
                    href='/icons/icon-144x144.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='152x152'
                    href='/icons/icon-152x152.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='192x192'
                    href='/icons/icon-192x192.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='256x256'
                    href='/icons/icon-256x256.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='384x384'
                    href='/icons/icon-384x384.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='512x512'
                    href='/icons/icon-512x512.png'
                />

                <link rel='manifest' href='/manifest.json' />
                <link rel='shortcut icon' href='/favicon.ico' />

                <meta name='twitter:card' content='summary' />
                <meta name='twitter:url' content='https://yourdomain.com' />
                <meta name='twitter:title' content='PWA App' />
                <meta
                    name='twitter:description'
                    content='Best PWA App in the world'
                />
                <meta
                    name='twitter:image'
                    content='https://yourdomain.com/icons/icon-192x192.png'
                />
                <meta name='twitter:creator' content='@DavidWShadow' />

                <meta property='og:type' content='website' />
                <meta property='og:title' content='PWA App' />
                <meta
                    property='og:description'
                    content='Best PWA App in the world'
                />
                <meta property='og:site_name' content='PWA App' />
                <meta property='og:url' content='https://yourdomain.com' />
                <meta
                    property='og:image'
                    content='https://yourdomain.com/icons/icon-512x512.png'
                />
            </head>

            <body className={`${geistMono.variable} antialiased font-mono`}>
                <Header />
                <Copyright />
                <Suspense fallback={<Loading />}>{children}</Suspense>
            </body>
        </html>
    );
}
